### ISSUE TITLE
email not configured as it use to be 

### ISSUE THREAD

**Issue by Aditya2Mathur** [shashankdixit047/randomise#3]
email jo hain uska code ye hain  {current}

<ul>
                                <li><a href="tel:011 4180 9120"><i class="far fa-phone"></i>011 4180 9120</a></li>
                                <li><a href="mailto:info@a3mcontracts.com">
                                    
                                    <i
                                            class="far fa-envelope"></i>info@a3mcontracts.com</a></li>
                            </ul>
                            
                            
                            it needs to be i nfoooo not info

**Comment by Aditya2Mathur** [comment]
@shashankdixit047 please assign this to me as this is my first contribution and I am in learining

**Comment by shashankdixit047** [comment]
@Aditya2Mathur create PR 

for others he is learning and doing random contribution

**Comment by shashankdixit047** [comment]
PR ??
